version: '3.8'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
  
  app-service:
    build: ./app-service
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
  
  auth-service:
    build: ./auth-service
    depends_on:
      - rabbitmq